version: '3.1'
services:
  web:
    build: ./odoo-docker
    image: odoo:raspberry
    depends_on:
      - db
    ports:
      - "7979:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  odoo-data:
  db:
